### ISSUE TITLE
IE不兼容

### ISSUE THREAD

**Issue by hansumff** [xLong1029/xlong-website-cms#1]

**Comment by xLong1029** [comment]
您好，IE浏览器图片不显示的问题已修复，之前是用读取文件流的方式显示图片，目前已改成读取文件路径显示

**Comment by hansumff** [comment]
新bug，导航部分二级菜单有问题

**Comment by xLong1029** [comment]
> 大佬，IE下header部分的二级菜单有bug

你那边测是IE哪个版本呢，我这边再测试修改一下

**Comment by hansumff** [comment]
刚试了下，chrome下也是同样的问题

**Comment by xLong1029** [comment]
> 刚试了下，chrome下也是同样的问题

好的，我这边再排查一下

**Comment by xLong1029** [comment]
> 刚试了下，chrome下也是同样的问题

导航菜单和轮播图的BUG已修复，是babel的问题

**Comment by hansumff** [comment]
优秀

**Comment by hansumff** [comment]
在云服务器上直接npm start启动就行？是不是还需要配置启动项

**Comment by xLong1029** [comment]
> 在云服务器上直接npm start启动就行？是不是还需要配置启动项

此项目我还未在云服务器上配置过，目前还是开发阶段。你可以参考一下Egg官方应用部署文档：https://eggjs.org/zh-cn/core/deployment.html，启动项可按你需要的进行配置

**Comment by hansumff** [comment]
> > 在云服务器上直接npm start启动就行？是不是还需要配置启动项
> 
> 此项目我还未在云服务器上配置过，目前还是开发阶段。你可以参考一下Egg官方应用部署文档：[https://eggjs.org/zh-cn/core/deployment.html，启动项可按你需要的进行配置](https://eggjs.org/zh-cn/core/deployment.html%EF%BC%8C%E5%90%AF%E5%8A%A8%E9%A1%B9%E5%8F%AF%E6%8C%89%E4%BD%A0%E9%9C%80%E8%A6%81%E7%9A%84%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE)
